---
title: "Forecasting review (general information)"
output: 
  html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## **1. Potential review fields (Please feel free to suggest adding or deleting fields)**

* Ecological forecasting

    * Forest ecosystem  

    * Agriculture ecosystem

    * Marine ecosystem

    * Harmful Algal Bloom (HAB) forecasting

* Meteorology forecasting

    * Tidal/king tide forecasting (esp relevant for tidal and storm surge + SLR)

    * Bering Sea - ROMSNPZ forecasts of cold pool area

    * Freshwater flow

* Health forecasting

* Financial forecasting

* Energy forecasting

* Political/elections forecasting and sports forecasting

## **2. Potential review topics (Dietze et al., 2018; Please feel free to suggest adding or deleting topics)**

* Data

    * Repeated measurements

    * Interoperability

    * Latency

* Theory and methods

    * Technical advancements

    * Predictability and uncertainty (communication of uncertainty)

    * Model-data assimilation

    * Workflow

    * Skill assessment (reforecasts)

* Devops infrastructure

    * Transparency

    * Reproducibility

    * Accessibility

* Training, culture, and institutions

* Decision support

    * Partnership

    * Management

## **Example**

* Participants

    * A (Coordinator), B, C, D, E

* What are the key lessons we can learn from this field? (In presenting key lessons might be good to contrast to how forecasts for fisheries are carried out and communicated)

    * Methods; Devops infrastructure; Training, culture, and institutions; Decision support

* Do we have a contact person for an interview?

    * F

* Plan (who’s doing what)

    * Review devops infrastructure (A, B)

    * Review forecasting methods (C, E)

    * Interview F (D, E)

* Milestones and timeline

    * Review presentation/discussion in August 2021

* References

    * Predictive Ecosystem Analyzer ([PEcAn Project](https://flux.aos.wisc.edu/projects/2018/6/19/pecan); [PEcAn Book](https://pecanproject.github.io/pecan-documentation/master/project-overview.html)): Integrated informatics toolbox for ecosystem modeling

    * LeBauer D, et al. (2013) Facilitating feedbacks between field measurements and ecosystem models. Ecol Monogr 83:133–154

