---
title: 'Forecasting review working document'
output:
  
  html_document: default
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## **1. Ecological forecasting**

* Participants

    * xxx

    * xxx

* What are the key lessons we can learn from this field?

    * xxx

    * xxx

* Do we have a contact person for an interview?

    * xxx

    * xxx

* Plan (who’s doing what)

    * xxx

    * xxx

* Milestones and timeline

    * xxx

    * xxx

* References

    * [Ecological forecasting bibliographies](http://people.bu.edu/dietze/manuscripts/EcologicalForecasting2018OxfordBibliographies.pdf) from Dietze et al., 2018

    * xxx

    * xxx

## **2. Meteorology forecasting**

* Participants

    * xxx

    * xxx

* What are the key lessons we can learn from this field?

    * xxx

    * xxx

* Do we have a contact person for an interview?

    * xxx

    * xxx

* Plan (who’s doing what)

    * xxx

    * xxx

* Milestones and timeline

    * xxx

    * xxx

* References

    * xxx

    * xxx

## **3. Health forecasting**

* Participants

    * xxx

    * xxx

* What are the key lessons we can learn from this field?

    * xxx

    * xxx

* Do we have a contact person for an interview?

    * xxx

    * xxx

* Plan (who’s doing what)

    * xxx

    * xxx

* Milestones and timeline

    * xxx

    * xxx

* References

    * xxx

    * xxx

## **4. Financial forecasting**

* Participants

    * xxx

    * xxx

* What are the key lessons we can learn from this field?

    * xxx

    * xxx

* Do we have a contact person for an interview?

    * xxx

    * xxx

* Plan (who’s doing what)

    * xxx

    * xxx

* Milestones and timeline

    * xxx

    * xxx

* References

    * xxx

    * xxx

## **5. Energy forecasting**

* Participants

    * xxx

    * xxx

* What are the key lessons we can learn from this field?

    * xxx

    * xxx

* Do we have a contact person for an interview?

    * xxx

    * xxx

* Plan (who’s doing what)

    * xxx

    * xxx

* Milestones and timeline

    * xxx

    * xxx

* References

    * xxx

    * xxx

## **6. Political/elections forecasting and sports forecasting**

* Participants

    * xxx

    * xxx

* What are the key lessons we can learn from this field?

    * xxx

    * xxx

* Do we have a contact person for an interview?

    * xxx

    * xxx

* Plan (who’s doing what)

    * xxx

    * xxx

* Milestones and timeline

    * xxx

    * xxx

* References

    * xxx

    * xxx

