
---
title: 'Forecasting review bibliography'
output:
  word_document: default
  html_document: default
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
            
- N. Tolimieri, M. A. Haltuch, Q. Lee, M. G. Jacox, S. J. Bograd. 2018. Oceanographic drivers of sablefish recruitment in the California Current. Fisheries Oceanography. 27(5), 458-474, https://doi.org/10.1111/fog.12266
 
Abstract Oceanographic processes and ecological interactions can strongly influence recruitment success in marine fishes. Here, we develop an environmental index of sablefish recruitment with the goal of elucidating recruitment-environment relationships and informing stock assessment. We start with a conceptual life-history model for sablefish Anoplopoma fimbria on the US west coast to generate stage- and spatio-temporally-specific hypotheses regarding the oceanographic and biological variables likely influencing sablefish recruitment. Our model includes seven stages from pre-spawn female condition through benthic recruitment (age-0 fish) for the northern portion of the west coast U.S. sablefish stock (40°N–50°N). We then fit linear models and use model comparison to select predictors. We use residuals from the stock-recruitment relationship in the 2015 sablefish assessment as the dependent variable (thus removing the effect of spawning stock biomass). Predictor variables were drawn primarily from ROMS model outputs for the California Current Ecosystem. We also include indices of prey and predator abundance and freshwater input. Five variables explained 57\% of the variation in recruitment not accounted for by the stock-recruitment relationship in the sablefish assessment. Recruitment deviations were positively correlated with (i) colder conditions during the spawner preconditioning period, (ii) warmer water temperatures during the egg stage, (iii) stronger cross-shelf transport to near-shore nursery habitats during the egg stage, (iv) stronger long-shore transport to the north during the yolk-sac stage, and (v) cold surface water temperatures during the larval stage. This result suggests that multiple mechanisms likely affect sablefish recruitment at different points in their life history.
 
- Melissa A. Haltuch, Nick Tolimieri, Qi Lee, Michael G. Jacox. 2020. Oceanographic drivers of petrale sole recruitment in the California Current Ecosystem. Fisheries Oceanography. 29(2), 122-136, https://doi.org/10.1111/fog.12459
 
Abstract This paper investigates environmental drivers of U.S. West Coast petrale sole (Eopsetta jordani) recruitment as an initial step toward developing an environmental recruitment index that can inform the stock assessment in the absence of survey observations of age-0 and age-1 fish. First, a conceptual life history approach is used to generate life-stage-specific and spatio-temporally specific mechanistic hypotheses regarding oceanographic variables that likely influence survival at each life stage. Seven life history stages are considered, from female spawner condition through benthic recruitment as observed in the Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey (age-2 fish). The study area encompasses the region from 40 to 48°N in the California Current Ecosystem. Hypotheses are tested using output from a regional ocean reanalysis model outputs and model selection techniques. Four oceanographic variables explained 73\% of the variation in recruitment not accounted for by estimates based exclusively on the spawning stock size. Recruitment deviations were (a) positively correlated with degree days during the female precondition period, (b) positively correlated with mixed-layer depth during the egg stage, (c) negatively correlated with cross-shelf transport during the larval stage, and (d) negatively correlated with cross-shelf transport during the benthic juvenile stage. While multiple mechanisms likely affect petrale sole recruitment at different points during their life history, the strength of the relationship is promising for stock assessment and integrated ecosystem assessment applications.
 
- Thomas C. Wainwright. 2021. Ephemeral relationships in salmon forecasting: A cautionary tale. Progress in Oceanography. 193102522, https://doi.org/10.1016/j.pocean.2021.102522
 
The influence of climate on marine populations is important for predicting stock abundance of marine fishes, and has led to increasing interest in environment-based forecasts (EBFs) for harvest management. While some climate indices have proven useful for explaining fluctuations in Pacific salmon stock abundance, there have also been sudden failures of EBF models. I analyzed temporal patterns in prediction skill for a variety of climate and ecosystem indicators as predictors of marine survival for a coastal coho salmon stock by computing prediction skill for 29 climate and ecosystem indices across multiple time scales to explore patterns of skill across time. Results demonstrate that predictive skill of EBF models is often ephemeral, arising and falling suddenly across time. This behavior can be explained both on a statistical basis and as a consequence of complex interactions between climate, ecosystems, and populations involving both climate regime shifts and ecosystem phase transitions. Forecast failures are problematic for traditional forecast-dependent harvest management approaches. Solutions for this problem may include improved forecast models and improved climate and ecosystem indicators, but developing management systems that are robust to forecast uncertainty would provide a more reliable response to expected rapid ecosystem changes in response to climate.
 
- Jacob W. Bentley, Mathieu G. Lundy, Daniel Howell, Steven E. Beggs, Alida Bundy, Francisco {de Castro}, Clive J. Fox, Johanna J. Heymans, Christopher P. Lynam, Debbi Pedreschi, Pia Schuchert, Natalia Serpetti, Johnny Woodlock, David G. Reid. 2021. Refining Fisheries Advice With Stock-Specific Ecosystem Information. Frontiers in Marine Science. 8346, 10.3389/fmars.2021.602072
 
Although frequently suggested as a goal for ecosystem-based fisheries management, incorporating ecosystem information into fisheries stock assessments has proven challenging. The uncertainty of input data, coupled with the structural uncertainty of complex multi-species models, currently makes the use of absolute values from such models contentious for short-term single-species fisheries management advice. Here, we propose a different approach where the standard assessment methodologies can be enhanced using ecosystem model derived information. Using a case study of the Irish Sea, we illustrate how stock-specific ecosystem indicators can be used to set an ecosystem-based fishing mortality reference point (F<sub>ECO</sub>) within the “Pretty Good Yield” ranges for fishing mortality which form the present precautionary approach adopted in Europe by the International Council for the Exploration of the Sea (ICES). We propose that this new target, F<sub>ECO</sub>, can be used to scale fishing mortality down when the ecosystem conditions for the stock are poor and up when conditions are good. This approach provides a streamlined quantitative way of incorporating ecosystem information into catch advice and provides an opportunity to operationalize ecosystem models and empirical indicators, while retaining the integrity of current assessment models and the F<sub>MSY</sub>-based advice process.
 
