
---
title: 'Forecasting review bibliography'
output:
  word_document: default
  html_document: default
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
            
## Ecological Forecasting
- Clarissa R. Anderson, Elisa Berdalet, Raphael M. Kudela, Caroline K. Cusack, Joe Silke, Eleanor O’Rourke, Darcy Dugan, Molly McCammon, Jan A. Newton, Stephanie K. Moore, Kelli Paige, Steve Ruberg, John R. Morrison, Barbara Kirkpatrick, Katherine Hubbard, Julio Morell. 2019. **Scaling Up From Regional Case Studies to a Global Harmful Algal Bloom Observing System**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00250
 
 
- Clarissa R. Anderson, Raphael M. Kudela, Mati Kahru, Yi Chao, Leslie K. Rosenfeld, Frederick L. Bahr, David M. Anderson, Tenaya A. Norris. 2016. **Initial skill assessment of the California Harmful Algae Risk Mapping (C-HARM) system**. Harmful Algae. 59, 1-18, https://doi.org/10.1016/j.hal.2016.08.006
 
 
- John A. Barth, Susan E. Allen, Edward P. Dever, Richard K. Dewey, Wiley Evans, Richard A. Feely, Jennifer L. Fisher, Jonathan P. Fram, Burke Hales, Debby Ianson, Jennifer Jackson, Kim Juniper, Orest Kawka, Deborah Kelley, Jody M. Klymak, John Konovsky, P. Michael Kosro, Alexander Kurapov, Emilio Mayorga, Parker MacCready, Jan Newton, R. Ian Perry, Craig M. Risien, Marie Robert, Tetjana Ross, R. Kipp Shearman, Joe Schumacker, Samantha Siedlecki, Vera L. Trainer, Stephanie Waterman, Christopher E. Wingard. 2019. **Better regional ocean observing through cross-national cooperation: A case study from the Northeast Pacific**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00093
 
 
- Jacob W. Bentley, Mathieu G. Lundy, Daniel Howell, Steven E. Beggs, Alida Bundy, Francisco {de Castro}, Clive J. Fox, Johanna J. Heymans, Christopher P. Lynam, Debbi Pedreschi, Pia Schuchert, Natalia Serpetti, Johnny Woodlock, David G. Reid. 2021. **Refining Fisheries Advice With Stock-Specific Ecosystem Information**. Frontiers in Marine Science. 8, https://doi.org/10.3389/fmars.2021.602072
 
 
- David Chagaris, Katie Drew, Amy Schueller, Matt Cieri, Joana Brito, Andre Buchheister. 2020. **Ecological Reference Points for Atlantic Menhaden Established Using an Ecosystem Model of Intermediate Complexity**. Frontiers in Marine Science. 7, https://doi.org/10.3389/fmars.2020.606417
 
 
- Michael C. Dietze, Andrew Fox, Lindsay M. Beck-Johnson, Julio L. Betancourt, Mevin B. Hooten, Catherine S. Jarnevich, Timothy H. Keitt, Melissa A. Kenney, Christine M. Laney, Laurel G. Larsen, Henry W. Loescher, Claire K. Lunch, Bryan C. Pijanowski, James T. Randerson, Emily K. Read, Andrew T. Tredennick, Rodrigo Vargas, Kathleen C. Weathers, Ethan P. White. 2018. **Iterative near-term ecological forecasting: Needs, opportunities, and challenges**. Proceedings of the National Academy of Sciences of the United States of America. 115, 1424-1432, https://doi.org/10.1073/pnas.1710231115
 
 
- Katie Drew, Matthew Cieri, Amy M. Schueller, Andre Buchheister, David Chagaris, Geneviève Nesslage, Jason E. McNamee, James H. Uphoff. 2021. **Balancing Model Complexity, Data Requirements, and Management Objectives in Developing Ecological Reference Points for Atlantic Menhaden**. Frontiers in Marine Science. 8, https://doi.org/10.3389/fmars.2021.608059
 
 
- Jose A. Fernandes-Salvador, Keith Davidson, Marc Sourisseau, Marta Revilla, Wiebke Schmidt, Dave Clarke, Peter I. Miller, Paola Arce, Raúl Fernández, Luz Maman, Alexandra Silva, Callum Whyte, Maria Mateo, Patricia Neira, Marcos Mateus, Manuel Ruiz-Villarreal, Luis Ferrer, Joe Silke. 2021. **Current Status of Forecasting Toxic Harmful Algae for the North-East Atlantic Shellfish Aquaculture Industry**. Frontiers in Marine Science. 8, https://doi.org/10.3389/fmars.2021.666583
 
 
- Isabel Gutierrez-Montes, Maureen Arguedas, Felicia Ramirez-Aguero, Leida Mercado, Jorge Sellare. 2020. **Contributing to the construction of a framework for improved gender integration into climate-smart agriculture projects monitoring and evaluation: MAP-Norway experience**. Climatic Change. 158, 93-106, https://doi.org/10.1007/s10584-018-2231-1
 
 
- M. A. Haltuch, E. N. Brooks, J. Brodziak, J. A. Devine, K. F. Johnson, N. Klibansky, R. D.M. Nash, M. R. Payne, K. W. Shertzer, S. Subbey, B. K. Wells. 2019. **Unraveling the recruitment problem: A review of environmentally-informed forecasting and management strategy evaluation**. Fisheries Research. 217, 198-216, https://doi.org/10.1016/j.fishres.2018.12.016
 
 
- Cecilie Hansen, Richard D.M. Nash, Kenneth F. Drinkwater, Solfrid Sætre Hjøllo. 2019. **Management Scenarios Under Climate Change – A Study of the Nordic and Barents Seas**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00668
 
 
- Alistair J. Hobday, Claire M. Spillman, J. Paige Eveson, Jason R. Hartog. 2016. **Seasonal forecasting for decision support in marine fisheries and aquaculture**. Fisheries Oceanography. 25, 45-56, https://doi.org/10.1111/fog.12083
 
 
- Alistair J. Hobday, Jason R. Hartog, John P. Manderson, Katherine E. Mills, Matthew J. Oliver, Andrew J. Pershing, Samantha Siedlecki, Howard Browman. 2019. **Ethical considerations and unanticipated consequences associated with ecological forecasting for marine resources**. ICES Journal of Marine Science. 76, 1244-1256, https://doi.org/10.1093/icesjms/fsy210
 
 
- Anne Babcock Hollowed, Kirstin Kari Holsman, Alan C. Haynie, Albert J. Hermann, Andre E. Punt, Kerim Aydin, James N. Ianelli, Stephen Kasperski, Wei Cheng, Amanda Faig, Kelly A. Kearney, Jonathan C.P. Reum, Paul Spencer, Ingrid Spies, William Stockhausen, Cody S. Szuwalski, George A. Whitehouse, Thomas K. Wilderbuer. 2020. **Integrated Modeling to Evaluate Climate Change Impacts on Coupled Social-Ecological Systems in Alaska**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00775
 
 
- Daniel Howell, Amy M. Schueller, Jacob W. Bentley, Andre Buchheister, David Chagaris, Matthew Cieri, Katie Drew, Mathieu G. Lundy, Debbi Pedreschi, David G. Reid, Howard Townsend. 2021. **Combining Ecosystem and Single-Species Modeling to Provide Ecosystem-Based Fisheries Management Advice Within Current Management Systems**. Frontiers in Marine Science. 7, https://doi.org/10.3389/fmars.2020.607831
 
 
- Peter DF Isles, Francesco Pomati. 2021. **An operational framework for defining and forecasting phytoplankton blooms**. Frontiers in Ecology and the Environment. fee.2376, https://doi.org/10.1002/fee.2376
 
 
- Michael G. Jacox, Michael A. Alexander, Samantha Siedlecki, Ke Chen, Young Oh Kwon, Stephanie Brodie, Ivonne Ortiz, Desiree Tommasi, Matthew J. Widlansky, Daniel Barrie, Antonietta Capotondi, Wei Cheng, Emanuele Di Lorenzo, Christopher Edwards, Jerome Fiechter, Paula Fratantoni, Elliott L. Hazen, Albert J. Hermann, Arun Kumar, Arthur J. Miller, Douglas Pirhalla, Mercedes Pozo Buil, Sulagna Ray, Scott C. Sheridan, Aneesh Subramanian, Philip Thompson, Lesley Thorne, Hariharasubramanian Annamalai, Kerim Aydin, Steven J. Bograd, Roger B. Griffis, Kelly Kearney, Hyemi Kim, Annarita Mariotti, Mark Merrifield, Ryan Rykaczewski. 2020. **Seasonal-to-interannual prediction of North American coastal marine ecosystems: Forecast methods, mechanisms of predictability, and priority developments**. Progress in Oceanography. 183, https://doi.org/10.1016/j.pocean.2020.102307
 
 
- Sunny L. Jardine, Mary C. Fisher, Stephanie K. Moore, Jameal F. Samhouri. 2020. **Inequality in the Economic Impacts from Climate Shocks in Fisheries: The Case of Harmful Algal Blooms**. Ecological Economics. 176, https://doi.org/10.1016/j.ecolecon.2020.106691
 
 
- Isaac C. Kaplan, Cecilie Hansen, Hem Nalini Morzaria-Luna, Raphael Girardin, Kristin N. Marshall. 2020. **Ecosystem-Based Harvest Control Rules for Norwegian and US Ecosystems**. Frontiers in Marine Science. 7, https://doi.org/10.3389/fmars.2020.00652
 
 
- Isaac C. Kaplan, Gregory D. Williams, Nicholas A. Bond, Albert J. Hermann, Samantha A. Siedlecki. 2016. **Cloudy with a chance of sardines: Forecasting sardine distributions using regional climate models**. Fisheries Oceanography. 25, 15-27, https://doi.org/10.1111/fog.12131
 
 
- Isaac C. Kaplan, Kristin N. Marshall. 2016. **A Guinea pig's tale: Learning to review end-to-end marine ecosystem models for management applications**. ICES Journal of Marine Science. 73, 1715-1724, https://doi.org/10.1093/icesjms/fsw047
 
 
- Stefan Koenigstein, Matthias Ruth, Stefan Gößling-Reisemann. 2016. **Stakeholder-informed ecosystem modeling of ocean warming and acidification impacts in the barents sea region**. Frontiers in Marine Science. 3, https://doi.org/10.3389/fmars.2016.00093
 
 
- Fiona Nicholson, Rikke Krogshave Laursen, Rachel Cassidy, Luke Farrow, Linda Tendler, John Williams, Nicolas Surdyk, Gerard Velthof. 2020. **How can decision support tools help reduce nitrate and pesticide pollution from agriculture? A literature review and practical insights from the EU FAIRWAY project**. Water (Switzerland). 12, https://doi.org/10.3390/w12030768
 
 
- Erik Olsen, Isaac C. Kaplan, Cameron Ainsworth, Gavin Fay, Sarah Gaichas, Robert Gamble, Raphael Girardin, Cecilie H. Eide, Thomas F. Ihde, Hem Nalini Morzaria-Luna, Kelli F. Johnson, Marie Savina-Rolland, Howard Townsend, Mariska Weijerman, Elizabeth A. Fulton, Jason S. Link. 2018. **Ocean futures under ocean acidification, marine protection, and changing fishing pressures explored using a worldwide suite of ecosystem models**. Frontiers in Marine Science. 5, https://doi.org/10.3389/fmars.2018.00064
 
 
- Christophe Orazio, Rebeca Cordero Montoya, Margot Régolini, José G. Borges, Jordi Garcia-Gonzalo, Susana Barreiro, Brigite Botequim, Susete Marques, Róbert Sedmák, Róbert Smreček, Yvonne Brodrechtová, Vilis Brukas, Gherardo Chirici, Marco Marchetti, Ralf Moshammer, Peter Biber, Edwin Corrigan, Ljusk Ola Eriksson, Matteo Favero, Emil Galev, Geerten M. Hengeveld, Marius Kavaliauskas, Gintautas Mozgeris, Rudolf Navrátil, Maarten Nieuwenhuis, Ivan Paligorov, Davide Pettenella, Andrius Stanislovaitis, Margarida Tomé, Renats Trubins, Ján Tuček, Matteo Vizzarri, Ida Wallin, Hans Pretzsch, Ola Sallnäs. 2017. **Decision support tools and strategies to simulate forest landscape evolutions integrating forest owner behaviour: A review from the case studies of the European project, INTEGRAL**. Sustainability (Switzerland). 9, https://doi.org/10.3390/su9040599
 
 
- Mark R. Payne, Alistair J. Hobday, Brian R. MacKenzie, Desiree Tommasi, Danielle P. Dempsey, Sascha M.M. Fässler, Alan C. Haynie, Rubao Ji, Gang Liu, Patrick D. Lynch, Daniela Matei, Anna K. Miesner, Katherine E. Mills, Kjersti O. Strand, Ernesto Villarino. 2017. **Lessons from the first generation of marine ecological forecast products**. Frontiers in Marine Science. 4, https://doi.org/10.3389/fmars.2017.00289
 
 
- Frank Pennekamp, Alison C. Iles, Joshua Garland, Georgina Brennan, Ulrich Brose, Ursula Gaedke, Ute Jacob, Pavel Kratina, Blake Matthews, Stephan Munch, Mark Novak, Gian Marco Palamara, Björn C. Rall, Benjamin Rosenbaum, Andrea Tabi, Colette Ward, Richard Williams, Hao Ye, Owen L. Petchey. 2019. **The intrinsic predictability of ecological time series and its potential to guide forecasting**. Ecological Monographs. 89, https://doi.org/10.1002/ecm.1359
 
 
- Jonathan C.P. Reum, Julia L. Blanchard, Kirstin K. Holsman, Kerim Aydin, Anne B. Hollowed, Albert J. Hermann, Wei Cheng, Amanda Faig, Alan C. Haynie, André E. Punt. 2020. **Ensemble Projections of Future Climate Change Impacts on the Eastern Bering Sea Food Web Using a Multispecies Size Spectrum Model**. Frontiers in Marine Science. 7, https://doi.org/10.3389/fmars.2020.00124
 
 
- Jörn O. Schmidt, Steven J. Bograd, Haritz Arrizabalaga, José L. Azevedo, Steven J. Barbeaux, John A. Barth, Tim Boyer, Stephanie Brodie, Juan José Cárdenas, Scott Cross, Jean Noël Druon, Agneta Fransson, Jason Hartog, Elliott L. Hazen, Alistair Hobday, Michael Jacox, Johannes Karstensen, Sven Kupschus, Jon Lopez, Lauro A.S.P. Madureira, José E. Martinelli Filho, Patricia Miloslavich, Catarina P. Santos, Kylie Scales, Sabrina Speich, Matthew B. Sullivan, Amber Szoboszlai, Desiree Tommasi, Douglas Wallace, Stephani Zador, Paulo Antônio Zawislak. 2019. **Future Ocean Observations to Connect Climate, Fisheries and Marine Ecosystems**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00550
 
 
- Beth A. Stauffer, Holly A. Bowers, Earle Buckley, Timothy W. Davis, Thomas H. Johengen, Raphael Kudela, Margaret A. McManus, Heidi Purcell, G. Jason Smith, Andrea Vander Woude, Mario N. Tamburri. 2019. **Considerations in harmful algal bloom research and monitoring: Perspectives from a consensus-building workshop and technology testing**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00399
 
 
- Desiree Tommasi, Yvonne deReynier, Howard Townsend, Chris J. Harvey, William H. Satterthwaite, Kristin N. Marshall, Isaac C. Kaplan, Stephanie Brodie, John C. Field, Elliott L. Hazen, Stefan Koenigstein, Joshua Lindsay, Kathleen Moore, Barbara Muhling, Lisa Pfeiffer, James A. Smith, Jonathan Sweeney, Brian Wells, Michael G. Jacox. 2021. **A Case Study in Connecting Fisheries Management Challenges With Models and Analysis to Support Ecosystem-Based Management in the California Current Ecosystem**. Frontiers in Marine Science. 8, https://doi.org/10.3389/fmars.2021.624161
 
 
- Desiree Tommasi, Charles A. Stock, Alistair J. Hobday, Rick Methot, Isaac C. Kaplan, J. Paige Eveson, Kirstin Holsman, Timothy J. Miller, Sarah Gaichas, Marion Gehlen, Andrew Pershing, Gabriel A. Vecchi, Rym Msadek, Tom Delworth, C. Mark Eakin, Melissa A. Haltuch, Roland Séférian, Claire M. Spillman, Jason R. Hartog, Samantha Siedlecki, Jameal F. Samhouri, Barbara Muhling, Rebecca G. Asch, Malin L. Pinsky, Vincent S. Saba, Sarah B. Kapnick, Carlos F. Gaitan, Ryan R. Rykaczewski, Michael A. Alexander, Yan Xue, Kathleen V. Pegion, Patrick Lynch, Mark R. Payne, Trond Kristiansen, Patrick Lehodey, Francisco E. Werner. 2017. **Managing living marine resources in a dynamic environment: The role of seasonal to decadal climate forecasts**. Progress in Oceanography. 152, 15-49, https://doi.org/10.1016/j.pocean.2016.12.011
 
 
- Désirée Tommasi, Charles A. Stock, Kathleen Pegion, Gabriel A. Vecchi, Richard D. Methot, Michael A. Alexander, David M. Checkley. 2017. **Improved management of small pelagic fisheries through seasonal climate prediction:**. Ecological Applications. 27, 378-388, https://doi.org/10.1002/eap.1458
 
 
- Howard Townsend, Chris J. Harvey, Yvonne deReynier, Dawn Davis, Stephani G. Zador, Sarah Gaichas, Mariska Weijerman, Elliott L. Hazen, Isaac C. Kaplan. 2019. **Progress on Implementing Ecosystem-Based Fisheries Management in the United States Through the Use of Ecosystem Models and Analysis**. Frontiers in Marine Science. 6, https://doi.org/10.3389/fmars.2019.00641
 
 
- Elisabeth Van Beveren, Hugues P. Benoît, Daniel E. Duplisea. 2021. **Forecasting fish recruitment in age-structured population models**. Fish and Fisheries. https://doi.org/10.1111/faf.12562
 
 
- Thomas C. Wainwright. 2021. **Ephemeral relationships in salmon forecasting: A cautionary tale**. Progress in Oceanography. 193, https://doi.org/10.1016/j.pocean.2021.102522
 
 
- Ethan P. White, Glenda M. Yenni, Shawn D. Taylor, Erica M. Christensen, Ellen K. Bledsoe, Juniper L. Simonis, S. K.Morgan Ernest. 2019. **Developing an automated iterative near-term forecasting system for an ecological study**. Methods in Ecology and Evolution. 10, 332-344, https://doi.org/10.1111/2041-210X.13104
 
 
- George A. Whitehouse, Kerim Y. Aydin, Anne B. Hollowed, Kirstin K. Holsman, Wei Cheng, Amanda Faig, Alan C. Haynie, Albert J. Hermann, Kelly A. Kearney, André E. Punt, Timothy E. Essington. 2021. **Bottom–Up Impacts of Forecasted Climate Change on the Eastern Bering Sea Food Web**. Frontiers in Marine Science. 8, https://doi.org/10.3389/fmars.2021.624301
 
 
